# Generated by Django 4.2.1 on 2023-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_remove_employeerole_permissions"),
        ("authentication", "0003_alter_permission_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
