version: '3'
services:
  backend:
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    build: ./wombase_backend/
    container_name: wombase-backend
    ports:
      - "8000:8000"
    volumes:
      - ./wombase_backend/server:/opt/server
