# Generated by Django 4.1.7 on 2023-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('permissions', models.ManyToManyField(blank=True, to='authentication.permission')),
            ],
        ),
    ]
