# Generated by Django 4.2.1 on 2023-10-28 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0002_alter_employeerole_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeerole",
            name="permissions",
        ),
    ]
