name: Push Docker Image to ECR
on:
  push:
    branches:
      - deployment

jobs:
  build-and-push:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, Tag and Push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: wombase
        IMAGE_TAG: latest
      run: |
        docker build \
        --build-arg "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
        --build-arg "DB_NAME=${{ secrets.DB_NAME }}" \
        --build-arg "DB_USER=${{ secrets.DB_USER }}" \
        --build-arg "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
        --build-arg "DB_HOST=${{ secrets.DB_HOST }}" \
        -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG